"""
Renders a finished review as an email report.

Plain HTML with inline styles and a table layout, because that is what mail
clients render predictably: no stylesheet, no flexbox, no web fonts. Every
value the model produced is escaped on the way in — a risk description is
untrusted text, and this one goes in an email.
"""

import json
from html import escape

from enums.RiskSeverity import RiskSeverity
from schemas.legal_review import DocumentAdvice
from utils.legal_responses import advice_body

SEVERITY_COLOURS = {
    RiskSeverity.CRITICAL: "#b3261e",
    RiskSeverity.HIGH: "#b54708",
    RiskSeverity.MEDIUM: "#8a5300",
    RiskSeverity.LOW: "#4b5563",
}


def subject_for(documents: list[DocumentAdvice], project_name: str = "") -> str:
    """A subject line that says what arrived and whether it needs attention."""
    counts = severity_counts(documents)
    worst = next((severity for severity in reversed(list(RiskSeverity)) if counts.get(severity)), None)

    where = f" — {project_name}" if project_name else ""
    risks = f"{sum(counts.values())} risk(s)"
    headline = f", worst {worst.value}" if worst else ", none flagged"

    return f"Legal review of {len(documents)} document(s){where}: {risks}{headline}"


def severity_counts(documents: list[DocumentAdvice]) -> dict[RiskSeverity, int]:
    """How many risks of each severity across the whole review."""
    counts: dict[RiskSeverity, int] = {}

    for document in documents:
        for risk in document.advice.key_risks:
            counts[risk.severity] = counts.get(risk.severity, 0) + 1

    return counts


def render_html(task_id: str, documents: list[DocumentAdvice], project_name: str = "") -> str:
    """The report body: the totals, then one section per document."""
    counts = severity_counts(documents)

    totals = " ".join(
        f'<span style="display:inline-block;padding:2px 8px;margin-right:6px;border-radius:6px;'
        f'background:#f1efe8;color:{SEVERITY_COLOURS[severity]};font-weight:700;font-size:12px">'
        f"{counts[severity]} {severity.value}</span>"
        for severity in RiskSeverity
        if counts.get(severity)
    )

    header = f"<h1 style='font-size:20px;margin:0 0 4px'>Legal review {escape(task_id)}</h1>"
    if project_name:
        header += f"<p style='margin:0 0 12px;color:#5f636b'>{escape(project_name)}</p>"

    body = "".join(_document_section(document) for document in documents)

    return (
        "<div style=\"font-family:-apple-system,'Segoe UI',Roboto,Arial,sans-serif;color:#1c1e22;max-width:720px\">"
        f"{header}"
        f"<p style='margin:0 0 16px'>{len(documents)} document(s) reviewed. {totals or 'No risks flagged.'}</p>"
        f"{body}"
        "<p style='color:#5f636b;font-size:12px;margin-top:24px'>"
        "Generated by the Legal Review Agent. The full advice is attached as JSON. "
        "This is a model's reading of the documents, not legal advice.</p>"
        "</div>"
    )


def _document_section(document: DocumentAdvice) -> str:
    advice = document.advice
    risks = sorted(advice.key_risks, key=lambda risk: risk.severity, reverse=True)

    rows = "".join(_risk_row(risk) for risk in risks) or (
        "<tr><td style='padding:8px;color:#5f636b'>No key risks flagged.</td></tr>"
    )

    attention = ""
    if advice.review_decision.needs_attention:
        attention = (
            "<p style='margin:0 0 8px;padding:8px;background:#fbefd6;color:#8a5300;border-radius:6px'>"
            "The model had a question that nobody answered in time. Treat this advice as a draft.</p>"
        )

    return (
        "<div style='margin:0 0 24px;padding:16px;border:1px solid #e3e0d6;border-radius:10px'>"
        f"<h2 style='font-size:16px;margin:0 0 4px'>{escape(document.pdf_key)}</h2>"
        f"<p style='margin:0 0 8px;color:#5f636b;font-size:12px'>{escape(advice.review_decision.value)}</p>"
        f"{attention}"
        f"<p style='margin:0 0 12px'>{escape(advice.summary)}</p>"
        f"<table style='border-collapse:collapse;width:100%'>{rows}</table>"
        "</div>"
    )


def _risk_row(risk) -> str:
    colour = SEVERITY_COLOURS.get(risk.severity, "#4b5563")

    where = " · ".join(filter(None, [escape(risk.location), f"p. {risk.page}" if risk.page else ""]))
    quote = ""
    if risk.quote:
        flag = "" if risk.quote_verified else " <em style='color:#8a5300'>(unverified quote)</em>"
        quote = (
            f"<div style='margin-top:4px;padding-left:8px;border-left:3px solid #cfcabc;color:#5f636b;font-size:13px'>"
            f"“{escape(risk.quote)}”{flag}</div>"
        )

    return (
        "<tr>"
        f"<td style='padding:6px 8px;vertical-align:top;white-space:nowrap;color:{colour};font-weight:700;font-size:12px'>"
        f"{escape(risk.severity.value.upper())}</td>"
        f"<td style='padding:6px 8px;vertical-align:top'>{escape(risk.description)}"
        f"{f'<div style=\"color:#5f636b;font-size:12px\">{where}</div>' if where else ''}"
        f"{quote}</td>"
        "</tr>"
    )


def render_json(task_id: str, documents: list[DocumentAdvice]) -> bytes:
    """The attachment: the same advice the API serves, as a file."""
    payload = {
        "task_id": task_id,
        "document_count": len(documents),
        "documents": [advice_body(document.pdf_key, document.advice) for document in documents],
    }

    return json.dumps(payload, indent=2).encode("utf-8")
